In [48]:
import torch

### Using automatic differentiation with pytorch:

###### 1st eaxample with function: $y = 3\mathbf{x}^T \mathbf{x}$.

In [49]:
x = torch.arange(4.0)
x.requires_grad_(True)
y = 3 * torch.dot(x, x)

###### Using backward to get the gradient related to X

In [50]:
y.backward()
x.grad

tensor([ 0.,  6., 12., 18.])

In [51]:
x.grad == 6 * x

tensor([True, True, True, True])

###### Gradient must be mannualy reset:

In [52]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

###### 2nd eaxample with function: $y = 3\mathbf{x}² -  2\mathbf{z}$.

In [53]:
x = torch.arange(3.0)
z = torch.arange(3.0,6.0)
x.requires_grad_(True)
z.requires_grad_(True)
y = 3*x**2 - 2*z
external_grad = torch.tensor([1., 1., 1.]) # setting gradient shape (necessary!)
y.backward(gradient=external_grad)
print(x.grad)
print(z.grad)
print(x.grad == 6*x)
print(z.grad == -2)

tensor([ 0.,  6., 12.])
tensor([-2., -2., -2.])
tensor([True, True, True])
tensor([True, True, True])


###### When y is a vector:

In [ ]:
x = torch.tensor([0., 1., 2., 3.],requires_grad=True)
y = x * x
y.sum().backward() 
x.grad # Sum of gradients (in a minibatch)

tensor([0., 2., 4., 6.])

### Detaching
###### Tensor detached do not require grad, useful for RF learning, and using on predictions...